---
title: "iLifespan lab log"
output:
  html_document:
    toc: yes
---
</br>  

#2014

## September

### September 12
Topic: [Basic line graphs][20140912]  
Study: OCTO TWIN  
In focus: Hypertension and Cognition   
Code source: [Hypertension and Cognition](https://github.com/IALSA/Hypertension-and-Cognition/tree/gh-pages/LabLog) project, private repository
</br>


### September 19
Topic: [From Raw to Draw][20140919] 
Study: OCTO TWIN
In focus: Hypertension and Cognition. Session introduced the concept of datastages. Basic map of dataflow is introduced.  
Code source: [Hypertension and Cognition](https://github.com/IALSA/Hypertension-and-Cognition/tree/gh-pages/LabLog) project, private repository
</br>


### September 26 
Topic: [Part 1 : Reshaping Data][20140926] 
Study: OCTO TWIN
In focus: Personality and Dementia  
Code source: [Personality and Dementia](https://github.com/IALSA/Personality-and-Dementia/tree/master/Reports/LabLog) project, private repository
</br> </br> </br>


## October

### October 3 
Topic: [Part 2: Graphing Data][20141003] 
Study: OCTO TWIN
In focus: Personality and Dementia   
Code source: [Personality and Dementia](https://github.com/IALSA/Personality-and-Dementia/tree/master/Reports/LabLog) project, private repository
</br> 


### October 10
Topic: [Intro to Reproducible Research (Demo)][20141010]  
Study: n/a  
In focus: Traditional vs Reproducible research paradigm  
Note: first draft of the lecture presented at [COAG Colloquium 2014F](http://ialsa.github.io/COAG-colloquium-2014F/), see final draft on [Toolbox and Toolset of Reproducible Research](http://ialsa.github.io/COAG-colloquium-2014F/2014-10-14-Toolbox-and-Skillset.html)
</br> 

### October 17   
Topic: [Data Manipulation (Demo)][20141017]   
Study: [NLSY](https://www.nlsinfo.org/investigator/pages/login.jsp)      
In focus: Religiosity in Young Adults, [NLSY97](https://www.nlsinfo.org/investigator/pages/login.jsp)      
Note: first draft of the lecture presented at [COAG Colloquium 2014F](http://ialsa.github.io/COAG-colloquium-2014F/), see final draft  on [RR Skills (1): Data Manipulation](http://ialsa.github.io/COAG-colloquium-2014F/2014-10-21-Data-Manipulation.html)   
Code source: [Reports](https://github.com/IALSA/COAG-colloquium-2014F/tree/LCM-sequence/Reports) from the COAG Colloquium 2014F lecture series on methodology and reproducible research, public repository.
</br> 




### October 31   
Topic: [Graph Production (Demo)][20141031]   
Study: [NLSY](https://www.nlsinfo.org/investigator/pages/login.jsp)    
In focus: Religiosity in Young Adults, [NLSY97](https://www.nlsinfo.org/investigator/pages/login.jsp)  
Note: first draft of the lecture presented at [COAG Colloquium 2014F](http://ialsa.github.io/COAG-colloquium-2014F/), see final draft  on [RR Basic Skills (2): Graph Production](http://ialsa.github.io/COAG-colloquium-2014F/2014-11-04-Producing-Graphs.html)  
Code source: [Reports](https://github.com/IALSA/COAG-colloquium-2014F/tree/LCM-sequence/Reports) from the COAG Colloquium 2014F lecture series on methodology and reproducible research, public repository.
</br> </br> </br>


## November

### November 7   
Topic: [Establishing Data Access: Curating a Study][20141107]   
Study: multiple    
In focus: Laying out the workflow for preparing the data of  varopis IALSA studies for analysis  
</br> 

### November 14   
Topic: [Demo: Statistical Modeling][20141114]   
Study: [NLSY](https://www.nlsinfo.org/investigator/pages/login.jsp)   
In focus: creating model objects in R
Note: first draft of the lecture presented at [COAG Colloquium 2014F](http://ialsa.github.io/COAG-colloquium-2014F/), see final draft  on [RR Basic Skills (3): Statistical modeling](http://ialsa.github.io/COAG-colloquium-2014F/2014-11-18-Statistical-Modeling.html)  
Code source: [Reports](https://github.com/IALSA/COAG-colloquium-2014F/tree/LCM-sequence/Reports) from the COAG Colloquium 2014F lecture series on methodology and reproducible research, public repository.
</br> 

### November 28   
Topic: [Demo: Dynamic Reporting][20141128]   
Study: [NLSY](https://www.nlsinfo.org/investigator/pages/login.jsp)  
In focus: production of dynamic documents for analyzing sequences of statistical models   
Note: first draft of the lecture presented at [COAG Colloquium 2014F](http://ialsa.github.io/COAG-colloquium-2014F/), see final draft  on [RR Basic Skills (4): Dynamic Reporting](http://ialsa.github.io/COAG-colloquium-2014F/2014-12-02-Dynamic-Reporting.html)  
Code source: [Reports](https://github.com/IALSA/COAG-colloquium-2014F/tree/LCM-sequence/Reports) from the COAG Colloquium 2014F lecture series on methodology and reproducible research, public repository.
</br> </br> </br>


# 2015 

## January

### January 23
Topic: Getting back with study curating.  
Study:  multiple  
In focus: TBA  



[20140912]:./2014-09-12-Line-graphs-OCTO.html
[20140919]:./2014-09-19-From-Raw-to-Draw.html
[20140926]:./2014-09-26-Dementia-Personality-OCTO.html
[20141003]:./2014-10-03-Dementia-Personality-OCTO-Part2.html
[20141010]:./2014-10-10-Intro-to-RR-Demo.html
[20141017]:./2014-10-21-Data-Manipulation-firstDraft.html
[20141031]:./2014-10-31-Producing-Graphs-Demo.html
[20141107]:./2014-11-07-Curating-a-Study.html
[20141114]:./2014-11-14-Statistical-Modeling-Demo.html
[20141128]:./2014-11-28-Dynamic-Reporting-Demo.html


